install: pip install -U coveralls .

language: python

python:
    - 3.6
    # - 3.5
    # - 3.4
    # - 3.3
    - 2.7
    # - 2.6

# We only need to run flake8 on 2.7
matrix:
    include:
        - name: "2.7 flake8"
          python: "2.7"
          install: "pip install flake8"
          script: "flake8 --ignore=E501 yamiconfig"

script:
    - coverage run --source="yamiconfig" -p -m py.test
    - coverage combine
    - coverage report -m


# after_success:
#     - coveralls
